### PR TITLE
contributor added

### PR DESCRIPTION
**Pull request by iamhariom0228**
#1

### CODE REVIEW

**Comment by iamhariom0228** [comment]
Sir please add hacktoberfest-accepted label to it!

**Comment by sohan2410** [comment]
@iamhariom0228 can you please squash the commits

**Comment by iamhariom0228** [comment]
Ok sir sure...

**Comment by iamhariom0228** [comment]
done sir please check

**Comment by iamhariom0228** [comment]
@sohan2410  sir please check

**Pull request merged**
