### PR TITLE
Pull request template

### PR DESCRIPTION
**Pull request by iamhariom0228**
@sohan2410  sir , I have tried to incorporate the  things which are necessary in a pull request template . Have an eye on it.

### CODE REVIEW

**Comment by sohan2410** [comment]
@iamhariom0228 please refer the GtiHub docs for PR template once again

**Comment by iamhariom0228** [comment]
Sure sir

**Comment by iamhariom0228** [comment]
Sir I am not understanding what more to add, can you please explain a bit what I am missing...

**Comment by sohan2410** [comment]
@iamhariom0228 you need to make file in `.github/pull_request_template.md`

**Comment by sohan2410** [comment]
@iamhariom0228 it should be .github/ not github/

**Comment by sohan2410** [comment]
Now please squash the commits

**Comment by iamhariom0228** [comment]
Done sir @sohan2410

**Comment by sohan2410** [comment]
Great! 🚀

**Comment by sohan2410** [comment]
Solved #2

**Pull request merged**
