### PR TITLE
Satyabrat_Ojha info.md added

### LINKED ISSUE #1: First time contribution
- Fork this repo and clone into your local system.
- Create a folder
`CONTRIBUTORS/${college_name}/${current_year_of_course}/${your_name}/info.md`
- Write a short note about yourself in info.md

### PR DESCRIPTION
**Pull request by Satyabrat-Ojha**
## Reference to the issue ✔️

Issue fixes #1 First time contribution : added 

## Proposed Changes ✔️

created a directory in
[GitFest](https://github.com/sohan2410/GitFest)/[CONTRIBUTORS](https://github.com/sohan2410/GitFest/tree/main/CONTRIBUTORS)/[ABV-IIITM](https://github.com/sohan2410/GitFest/tree/main/CONTRIBUTORS/ABV-IIITM)/2nd_Year/
Named as Satyabrat_Ojha and added a info.md file in it.

## Commands that you used to complete this issue ✔️

I wrote the git commands like -
git clone https://github.com/Satyabrat-Ojha/GitFest.git
git add .
git commit -m "message"
git push

### CODE REVIEW

**Comment by sohan2410** [comment]
@Satyabrat-Ojha please update PR description

**Comment by Satyabrat-Ojha** [comment]
@sohan2410 sir please check it out

**Comment by sohan2410** [comment]
PR description doesn't match with PR template

**Comment by Satyabrat-Ojha** [comment]
@sohan2410 sir is it fine now?

**Comment by sohan2410** [comment]
@Satyabrat-Ojha Add Commands that you used to complete this issue

**Comment by Satyabrat-Ojha** [comment]
> @Satyabrat-Ojha Add Commands that you used to complete this issue in PR description

done

**Pull request merged**
